Added Dasv4, Eav4, Easv4, and Lsv2
Azure/BatchExplorer-data pull request #90
Opened 2020-06-02 22:52 UTC by cRui861

2020-06-03 01:21 UTC, bgklein approved these changes

2020-06-03 01:21 UTC, bgklein commented on data/vm-sizes-list.json
> +            "^standard_e[0-9]*a_[v4]*$",
why the brackets around `[v4]

2020-07-17 21:27 UTC, dpwatrous requested changes
This PR looks totally fine to me, but until we have a better solution, I think we should try to make this more closely match the portal's VM size metadata. 

I'd love to get your thoughts on https://github.com/Azure/BatchExplorer-data/pull/91 instead as a way to make this process easier in the short term. (The portal has already added these VM sizes.)

2020-07-20 19:14 UTC, dpwatrous commented
Closing this PR since these changes are included in https://github.com/Azure/BatchExplorer-data/pull/91

2020-07-20 19:14 UTC, closed without merging